---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: mariadb
  labels:
    app: mariadb-instance
    component: data-science-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 20Gi

