---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-instance
  namespace: mariadb
  labels:
    app: mariadb-instance
    component: data-science-pipelines
spec:
  ports:
    - name: http
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb-instance
    component: data-science-pipelines